### ISSUE TITLE
Add CONTRIBUTORS file

### ISSUE THREAD

**Issue by jsanz** [jsanz/carto_cli#12]
Need to add a `CONTRIBUTORS` file to the repo with everyone helping here.

**Comment by arredond** [comment]
@jsanz Thanks for adding me here! Just a small note: my name's Álvaro, not Alberto hehe

Also, I'd rather use my personal email instead of my work one for these things. Thanks again!

**Comment by jsanz** [comment]
[fixed](https://github.com/jsanz/carto_cli/commit/70785fdbc6f186d3b72f73fc2802a95f15b68fa0) sorry :man_facepalming: 

![](https://media.giphy.com/media/gnJgBlPgHtcnS/giphy.gif)
